name: Docker Image Pull from DockerHub

on:
  workflow_dispatch: # allows manual trigger

jobs:
  save-image:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
#       run: docker pull nginx:latest
        run: docker pull ghcr.io/open-webui/open-webui

      - name: Save Docker image to tar
        run: docker save open-webui:latest -o open-webui.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: open-webui
          path: open-webui.tar
