name: Docker Login
on:
       workflow_dispatch:
jobs:
       login:
         runs-on: ubuntu-latest
         steps:
           - name: Login to Docker Hub
             uses: docker/login-action@v3
             with:
               username: ${{ secrets.DOCKER_USERNAME }}
               password: ${{ secrets.DOCKER_PASSWORD }}
           - name: Pull a public image
             run: docker pull hello-world
           - name: Run hello-world
             run: docker run hello-world
           - name: Verify image
             run: docker images
