name: Docker Image Push WebUI to DockerHub

on:
  workflow_dispatch: # manually trigger

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull image from Docker Hub
#       run: docker pull nginx:latest
        run: docker pull ghcr.io/open-webui/open-webui:latest

      - name: Tag image for user's repo
        run: docker tag ghcr.io/open-webui/open-webui:latest ${{ secrets.DOCKER_USERNAME }}/open-webui:latest
        
      - name: Push image to user's Docker Hub repo
        run: docker push ${{ secrets.DOCKER_USERNAME }}/open-webui:latest
