name: Fetch Binary

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: |
          curl -L https://ollama.com/download/ollama-linux-amd64.tar.zst -o linux-amd64.tar.zst

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ollama-binary
          files: linux-amd64.tar.zst
